### PR TITLE
Add new directives : "media-src" and "report-to"

### PR DESCRIPTION
**Pull request by akasake**
## Description
Add new directives : "media-src" and "report-to"

### CODE REVIEW

**Comment by akasake** [comment]
@RobinHoutevelts Can you confirm that these are the only things i need to add to add these directives?

**Comment by RobinHoutevelts** [comment]
@akasake I think the `report-to` directive only works in combination with the `Reporting-Endpoints` header.

Some documentation is at: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to
And also an example in the spec: https://w3c.github.io/reporting/#example-b1cea891

We don't need a `report-to` directive they can manage. `self` is also a wrong default/initial value.

Perhaps add a `Report endpoint` text field somewhere, where editors can fill in a url.
If that's populated we programmatically set the `Reporting-Endpoints` header and add the `report-to` directive ourselves.

```
Reporting-Endpoints: csp-endpoint="https://example.com/csp-reports"
Content-Security-Policy: ...; report-to csp-endpoint
```

**Comment by akasake** [comment]
@RobinHoutevelts I changed the code, locally it works 

Screenshot 2023-07-04 at 13 00 06

but after deploying to dev, there is no `Reporting-Endpoints`. Is this something for the serverboys?

**Comment by akasake** [comment]
I think we also need to be able to hide this field for sites where we don't want this on, what do you think?

**Review by RobinHoutevelts — APPROVED** [review]

**Comment by RobinHoutevelts** [comment]
> I think we also need to be able to hide this field for sites where we don't want this on, what do you think?

I wouldn't hide this feature. There is no negative server impact if an editor fills in something or not.
So I'd just let them do it themselves if they want to.

**Pull request merged**
